quickapp/urls.py
from django.urls import path
from .views import*

app_name="quickapp"
urlpatterns=[


path('login/',LoginView.as_view(),name="login"),

path("logout/",LogoutView.as_view(),name="logout"),


#client
path('',ClientHomeView.as_view(),name="clienthome"),
path('contact/',ClientContactView.as_view(),name="clientcontact"),
path('about/',ClientAboutView.as_view(),name="clientabout"),
path('profession/',ClientProfession.as_view(),name="clientprofession"),
path('events/',ClientEventView.as_view(),name="clientevent"),
path('employerregister/', EregisterView.as_view(),name="employerregister"),
path('jobseekerregister/', JregisterView.as_view(),name="jobseekerregister"),
path('username-checker/', IdCheckerView.as_view(),name="idchecker"),
path('job/<int:pk>/detail', ClientJobDetailView.as_view(),name="jobdetail"),
path("results/", ClientSearchView.as_view(), name="search"),
path("category/<int:pk>/list/", ClientCategoryDetailView.as_view(), name="clientcategorydetail"),





#admin
path("admin/home/",AdminHomeView.as_view(),name="adminhome"),
path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),
path("admin/jobcategory/<int:pk>/detail/",AdminJobCategoryDetailView.as_view(),name="adminjobcategorydetail"),
path("admin/jobcategory/create/",AdminJobCategoryCreateView.as_view(),name="adminjobcategorycreate"),
path("admin/jobcategory/<int:pk>/update/",AdminJobCategoryUpdateView.as_view(),name="adminjobcategoryupdate"),
path("admin/jobcategory/<int:pk>/delete/",AdminJobCategoryDeleteView.as_view(),name="adminjobcategorydelete"),
path("admin/job/list/",AdminJobListView.as_view(),name="adminjoblist"),
path("admin/job/<int:pk>/delete/",AdminJobDeleteView.as_view(),name="adminjobdelete"),
path("admin/job/<int:pk>/detail/",AdminJobDetailView.as_view(),name="adminjobdetail"),
#path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),


path("admin/profile/",AdminProfileView.as_view(),name="adminprofile"),

path("admin/employer/list/",EmployerListView.as_view(),name="employerlist"),
path("admin/employers/list/",AdminEmployerListView.as_view(),name="adminemployerlist"),
path("admin/employer/<int:pk>/detail/",AdminEmployerDetailView.as_view(),name="adminemployerdetail"),
path("admin/employer/<int:pk>/delete/",AdminEmployerDeleteView.as_view(),name="adminemployerdelete"),

path("admin/jobseeker/list/",AdminJobSeekerListView.as_view(),name="adminjobseekerlist"),
path("admin/jobseeker/<int:pk>/detail",AdminJobSeekerDetailView.as_view(),name="adminjobseekerdetail"),
path("admin/jobseeker/<int:pk>/delete/",AdminJobSeekerDeleteView.as_view(),name="adminjobseekerdelete"),


path("admin/slideshow/list/", AdminSlideShowListView.as_view(), name='adminslideshowlist'),
path("admin/slideshow/create/", AdminSlideShowCreateView.as_view(), name='adminslideshowcreate'),
path("admin/slideshow/<int:pk>/update/", AdminSlideShowUpdateView.as_view(), name='adminslideshowupdate'),
path("admin/slideshow/<int:pk>/delete/", AdminSlideShowDeleteView.as_view(), name='adminslideshowdelete'),


#employer
path("employer/home/",EmployerHomeView.as_view(),name="employerhome"),
path("employer/dashboard/",EmployerDashBoardView.as_view(),name="employerdashboard"),
path("employer/jobs/create/",EmployerJobCreateView.as_view(),name="employerjobcreate"),
path('employer/job/<int:pk>/delete/',EmployerJobDeleteView.as_view(), name="employerjobdelete"),
path('employer/job/<int:pk>/update/',EmployerJobUpdateView.as_view(), name="employerjobupdate"),
path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/<int:pk>/detail/",EmployerOwnDetailView.as_view(),name="employerowndetail"),

path("employer/category/",EmployerCategoryView.as_view(),name="employercategory"),
path("employer/category/create/",EmployerCategoryCreateView.as_view(),name="employercategorycreate"),
path('employer/category/<int:pk>/delete/',EmployerCategoryDeleteView.as_view(), name="employercategorydelete"),
path('employer/category/<int:pk>/update/',EmployerCategoryUpdateView.as_view(), name="employercategoryupdate"),
path("employer/logout/",EmployerLogoutView.as_view(),name="employerlogout"),





path("search/",EmployerSearchView.as_view(),name="employersearch"),

path("employer/home/jobs/list/",EmployerHomeJobListView.as_view(),name="employerhomejoblist"),
path("employer/category/list/",EmployerCategoryListView.as_view(),name="employercategorylist"),
path("employer/category/<int:pk>/detail/",EmployerCategoryDetailView.as_view(),name="employercategorydetail"),
path("employer/profile/<int:pk>/detail/",EmployerprofileDetailView.as_view(),name="employerprofile"),
path("employer/jobseeker/<int:pk>/detail/",EmployerJobseekerDetailView.as_view(),name="employerjobseeker"),
path("jobseeker/jobseekerapplied/", JobSeekerJobappliedmessagelView.as_view(), name="jobmessage"),











# jobseeker
path("jobseeker/home/",JobSeekerHomeView.as_view(),name="jobseekerhome"),
path("jobseeker/profile/list/",JobSeekerProfileListView.as_view(),name="jobseekerprofilelist"),

path("jobseeker/profile/detail/",JobSeekerProfileDetailView.as_view(),name="jobseekerprofiledetail"),
path("profile/detail/",ProfileDetailView.as_view(),name="profiledetail"),
path("jobseeker/profile/<int:pk>/update/",JobSeekerProfileUpdateView.as_view(),name="jobseekerprofileupdate"),
path("jobseeker/profile/<int:pk>/delete/",JobSeekerProfileDeleteView.as_view(),name="jobseekerprofiledelete"),


path("job/<int:pk>/apply",JobSeekerJobApplyView.as_view(),name="jobseekerjobapply"),


path("jobseeker/job/list",J_ApplyListView.as_view(),name="jobseekerjoblist"),
path("jobseeker/job/<int:pk>/detail",JobSeekerJobDetailView.as_view(),name="jobseekerjobdetail"),

#contact
path("contact/create/",ContactCreateView.as_view(),name="contactcreate"),
path("contact/list/",ContactListView.as_view(),name="contactlist"),
path("contact/<int:pk>/update/",ContactUpdateView.as_view(),name="contactupdate"),


#about
path("about/create/",AboutCreateView.as_view(),name="aboutcreate"),
path("about/list/",AboutListView.as_view(),name="aboutlist"),
path("about/<int:pk>/update/",AboutUpdateView.as_view(),name="aboutupdate"),




]

quickproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include("quickapp.urls")),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/employertemplates/employercategory.html
{% extends "employertemplates/employerbase.html" %}
{% load static %}
{% block home %}active{% endblock %}

{% block content %}



<h2><u>List of category</u></h2>
<table class="table">
	<thead>
		<tr>
			<th>S.N.</th>
			<th>title</th>
			<th>image</th>
			
			
		</tr>
	</thead>
	<tbody>
		{% for notice in ccl %}
		<tr>
			<td>{{forloop.counter}}</td>
					    

		    <td>{{notice.title}}</td>
		    <td><img src="{{notice.image.url}}" class="fluid" width="50"></td>
		   
		    
			

		</tr>
		{% endfor %}

	</tbody>


</table>


{% endblock %}

templates/employertemplates/employercategorycreate.html
 {% extends "employertemplates/employerbase.html" %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3>CategoryCreate</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button>ADD</button>
		</form>
		
	</div>
</div>


{% endblock %}

templates/employertemplates/employercategorydelete.html
{% extends "employertemplates/employerbase.html" %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<h1 colour="red">Are you sure?????</h1>
	<button>Yes</button>
	<button><a href="/employer/category/">NO</a></button>
	
</form>
{% endblock %}

templates/employertemplates/employerdashboard.html
{% extends "employertemplates/employerbase.html" %}
{% load static %}
{% block home %}active{% endblock %}

{% block content %}


<div class="row">
	
<div class="col"><h5><b> This is Employer Dashboard </b></h5></div>
<div class="col"><a href="{% url 'quickapp:employerjobcreate' %}"><button>Create JOB</button></a></div>


</div>






  <!-- Tables content -->
            <section class="tables-section">
                <!-- table1 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4"><u>Our Job lists</u></h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">S.N.</th>
                                <th scope="col">Job</th>
                                <th scope="col">Deadline</th>
                                <th scope="col">salary</th>
                                <th scope="col">Action</th>
			
                            </tr>
                        </thead>
                        <tbody>
		{% for notice in empjl %}
		<tr>
			<td>{{forloop.counter}}</td>
					    

		    <td><a href="{% url 'quickapp:employerjobdetail' notice.id %}">{{notice.title}}</a></td>

		    <td>{{notice.deadline}}</td>

		    <td>{{notice.salary}}</td>
			
			<td><a href="{% url 'quickapp:employerjobupdate' notice.id %}"><button>Update</button></a><br><br><a href="{% url 'quickapp:employerjobdelete' notice.id %}"><button>Delete</button></a></td>
			

		</tr>
		{% endfor %}

	</tbody>
                    </table>
                </div>
                <!--// table1 -->

                

            </section>

            <!--// Tables content -->





{% endblock %}

templates/employertemplates/employerdetail.html
 {% extends "employertemplates/employerbase.html" %}

{% block content %}
<div class="row">
	<div class="col-md-8">
		<h3 class="text-center">Employer Detail</h3>
		<table class="table table-striped">
			<tr>
				<th>User Name</th>
				<td>{{user.username}}</td>
			</tr>
			<tr>
				<th>Full Name</th>
				<td>{{empdetail.full_name}}</td>
			</tr>
			<tr>
				<th>Company Name</th>
				<td>{{empdetail.company_name}}</td>
			</tr>
			<tr>
				<th>Company Logo</th>
				<td><img src="{{empdetail.company_logo.url}}" width="100">
				</td>
			</tr>
			<tr>
				<th>Company Photo</th>
				<td><img src="{{empdetail.company_photo.url}}" width="150">
				</td>
				
			</tr>
			<tr>
				<th>Address</th>
				<td>{{empdetail.address}}</td>
			</tr>
			<tr>
				<th>Mobile</th>
				<td>{{empdetail.mobile}}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{empdetail.email}}</td>
			</tr>
			<tr>
				<th>Website</th>
				<td>{{empdetail.website}}</td>
			</tr>
			<tr>
				<th>Location</th>
				<td>{{empdetail.location}}</td>
			</tr>
			<tr>
				<th>About</th>
				<td>{{empdetail.about}}</td>
			</tr>
			
		</table>
	</div>
</div>





{% endblock %}

templates/employertemplates/employerhome.html
{% extends "employertemplates/employerbase.html" %}
{% load static %}


{% block content %}







            <div class="container-fluid">
                <div class="row">
                    <!-- Stats -->
                    <div class="outer-w3-agile col-xl">
                        <div class="stat-grid p-3 d-flex align-items-center justify-content-between bg-primary">
                            <div class="s-l">
                             <a href="{% url 'quickapp:employerhomejoblist' %}"><h5>Posted jobs</h5></a>

                            </div>
                            <div class="s-r">
                                <h6>340
                                    <i class="far fa-edit"></i>
                                </h6>
                            </div>
                        </div>

                        


                        <div class="stat-grid p-3 mt-3 d-flex align-items-center justify-content-between bg-warning">
                            <div class="s-l">
                            <a href="{% url 'quickapp:employercategorylist' %}"><h5>Categories</h5></a>

                            </div>
                            <div class="s-r">
                                <h6>190
                                    <i class="fas fa-users"></i>
                                </h6>
                            </div>
                        </div>
                    </div>
                    <!--// Stats -->


              </div>
            






{% endblock %}

templates/employertemplates/employerhomepostedjob.html
{% extends "employertemplates/employerbase.html" %}
{% load static %}


{% block content %}


            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center">Our Job lists</h2>
            <!--// main-heading -->


            <!-- Cards content -->
            <section class="cards-section">
                <div class="card-columns">
                	{% for notice in employerhmjoblist %}		
                    <div class="card">
                    	<a href="{% url 'quickapp:employerjobdetail' notice.id %}"><img class="card-img-top" src="{{notice.image.url}}" alt="Card image cap"></a>
                        
                        <div class="card-body">
                        	<a href="{% url 'quickapp:employerjobdetail' notice.id %}"><h5 class="card-title">{{notice.title}}</h5></a>
                            
                            <p class="card-text">
                                {{notice.description|truncatechars:100}}</p>
                            <a href="#" class="btn more mt-3" data-toggle="modal" data-target="#exampleModal{{forloop.counter}}">Read More</a>
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1	" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        	<a href="{% url 'quickapp:employerjobdetail' notice.id %}"><h5 class="modal-title" id="exampleModalLabel1">{{notice.title}}</h5></a>
                                            
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                        	<a href="{% url 'quickapp:employerjobdetail' notice.id %}"><img class="card-img-top" src="{{notice.image.url}}" alt="Card image cap"></a>
                                            <p class="paragraph-agileits-w3layouts my-3">{{notice.description}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /Modal -->
                        </div>
                    </div>
                    {% endfor %}
                    		
                </div>
            </section>






{% endblock %}

templates/employertemplates/employerjobcreate.html
 {% extends "employertemplates/employerbase.html" %}

{% block content %}
<div class="row">
	<div class="col-md-8 mx-auto">
		<h3>JobCreate</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-primary">ADD</button>
		</form>
		
	</div>
</div>


{% endblock %}

templates/employertemplates/employerjobdelete.html
{% extends "employertemplates/employerbase.html" %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<h3 colour="red">Are you sure?????</h3>
	<button>Yes</button>
	<button><a href="/employer/dashboard/">NO</a></button>
	
</form>
{% endblock %}

templates/employertemplates/employerjobseekerdetail.html
{% extends "employertemplates/employerbase.html" %}

{% load static %}

{% block content %}


<div class="row">
	<div class="col-md-8">
		<h3 class="text-center">Details of {{empjobseekerdetail.full_name}}</h3>
		<table class="table table-striped">
			<tr>
				<th>Full Name</th>
				<td>{{empjobseekerdetail.full_name}}</td>
			</tr>
			<tr>
				<th>Address</th>
				<td>{{empjobseekerdetail.address}}</td>
			</tr>
			<tr>
				<th>Mobile</th>
				<td>{{empjobseekerdetail.mobile}}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{empjobseekerdetail.email}}</td>
			</tr>
			<tr>
				<th>Skill</th>
				<td>{{empjobseekerdetail.skill}}</td>
			</tr>
			<tr>
				<th>DOB</th>
				<td>{{empjobseekerdetail.dob}}</td>
			</tr>
			<tr>
				<th>Education</th>
				<td>{{empjobseekerdetail.education}}</td>
			</tr>
			<tr>
				<img src="{{empjobseekerdetail.image.url}}" class="img-fluid" width="100">
			</tr>
		</table>
	</div>
</div>

{% endblock %}

templates/employertemplates/employerjobupdate.html
 {% extends "employertemplates/employerbase.html" %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3>JobForm</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button>Submit data</button>
		</form>
		
	</div>
</div>


{% endblock %}

templates/employertemplates/employerowndetail.html
 {% extends "employertemplates/employerbase.html" %}

{% block content %}
<div class="row">
	<div class="col-md-8">
		<h3 class="text-center">Employer Detail</h3>
		<table class="table table-striped">
			<tr>
				<th>Full Name</th>
				<td>{{empdeil.full_name}}</td>
			</tr>
			<tr>
				<th>Company Name</th>
				<td>{{empdeil.company_name}}</td>
			</tr>
			<tr>
				<th>Company Logo</th>
				<td>{{empdeil.company_logo}}</td>
			</tr>
			<tr>
				<th>Company Photo</th>
				<td>{{empdeil.company_photo}}</td>
			</tr>
			<tr>
				<th>Address</th>
				<td>{{empdeil.address}}</td>
			</tr>
			<tr>
				<th>Mobile</th>
				<td>{{empdeil.mobile}}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{empdeil.email}}</td>
			</tr>
			<tr>
				<th>Website</th>
				<td>{{empdeil.website}}</td>
			</tr>
			<tr>
				<th>Location</th>
				<td>{{empdeil.location}}</td>
			</tr>
			<tr>
				<th>About</th>
				<td>{{empdeil.about}}</td>
			</tr>
			<tr>
				<img src="{{empdeil.image.url}}" class="img-fluid">
			</tr>
		</table>
	</div>
</div>





{% endblock %}

templates/employertemplates/employersearch.html
{% extends "employertemplates/employerbase.html" %}


{% block content %}
<!-- <p>You are searching the data</p> -->
<!-- <h3>Search Results for {{request.GET.keyword}}</h3> -->
<h3>Search Results for <span class="text-info">{{request.GET.keyword}}</span></h3>


{% for job in search_results %}
      <li><a href="{% url 'quickapp:employerjobdetail' job.id %}">{{job.title}}</a></li>
      <img src="{{job.image.url}}" class="img-fluid" width="200">
      <li><a href="{% url 'quickapp:employerjobdetail' job.id %}"><span style="color:#000"	>{{job.description|truncatewords:"20"}}</span></a></li><br><br>

     

          {% empty %}
          <h4>No result found...</h4>
          <!-- search item payena vane yo message pass hunxa -->
{% endfor %}


{% endblock %}