quickapp/urls.py
from django.urls import path
from .views import*

app_name="quickapp"
urlpatterns=[


path('login/',LoginView.as_view(),name="login"),

path("logout/",LogoutView.as_view(),name="logout"),


#client
path('',ClientHomeView.as_view(),name="clienthome"),
path('contact/',ClientContactView.as_view(),name="clientcontact"),
path('about/',ClientAboutView.as_view(),name="clientabout"),
path('profession/',ClientProfession.as_view(),name="clientprofession"),
path('events/',ClientEventView.as_view(),name="clientevent"),
path('employerregister/', EregisterView.as_view(),name="employerregister"),
path('jobseekerregister/', JregisterView.as_view(),name="jobseekerregister"),
path('username-checker/', IdCheckerView.as_view(),name="idchecker"),
path('job/<int:pk>/detail', ClientJobDetailView.as_view(),name="jobdetail"),
path("results/", ClientSearchView.as_view(), name="search"),
path("category/<int:pk>/list/", ClientCategoryDetailView.as_view(), name="clientcategorydetail"),





#admin
path("admin/home/",AdminHomeView.as_view(),name="adminhome"),
path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),
path("admin/jobcategory/<int:pk>/detail/",AdminJobCategoryDetailView.as_view(),name="adminjobcategorydetail"),
path("admin/jobcategory/create/",AdminJobCategoryCreateView.as_view(),name="adminjobcategorycreate"),
path("admin/jobcategory/<int:pk>/update/",AdminJobCategoryUpdateView.as_view(),name="adminjobcategoryupdate"),
path("admin/jobcategory/<int:pk>/delete/",AdminJobCategoryDeleteView.as_view(),name="adminjobcategorydelete"),
path("admin/job/list/",AdminJobListView.as_view(),name="adminjoblist"),
path("admin/job/<int:pk>/delete/",AdminJobDeleteView.as_view(),name="adminjobdelete"),
path("admin/job/<int:pk>/detail/",AdminJobDetailView.as_view(),name="adminjobdetail"),
#path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),


path("admin/profile/",AdminProfileView.as_view(),name="adminprofile"),

path("admin/employer/list/",EmployerListView.as_view(),name="employerlist"),
path("admin/employers/list/",AdminEmployerListView.as_view(),name="adminemployerlist"),
path("admin/employer/<int:pk>/detail/",AdminEmployerDetailView.as_view(),name="adminemployerdetail"),
path("admin/employer/<int:pk>/delete/",AdminEmployerDeleteView.as_view(),name="adminemployerdelete"),

path("admin/jobseeker/list/",AdminJobSeekerListView.as_view(),name="adminjobseekerlist"),
path("admin/jobseeker/<int:pk>/detail",AdminJobSeekerDetailView.as_view(),name="adminjobseekerdetail"),
path("admin/jobseeker/<int:pk>/delete/",AdminJobSeekerDeleteView.as_view(),name="adminjobseekerdelete"),


path("admin/slideshow/list/", AdminSlideShowListView.as_view(), name='adminslideshowlist'),
path("admin/slideshow/create/", AdminSlideShowCreateView.as_view(), name='adminslideshowcreate'),
path("admin/slideshow/<int:pk>/update/", AdminSlideShowUpdateView.as_view(), name='adminslideshowupdate'),
path("admin/slideshow/<int:pk>/delete/", AdminSlideShowDeleteView.as_view(), name='adminslideshowdelete'),


#employer
path("employer/home/",EmployerHomeView.as_view(),name="employerhome"),
path("employer/dashboard/",EmployerDashBoardView.as_view(),name="employerdashboard"),
path("employer/jobs/create/",EmployerJobCreateView.as_view(),name="employerjobcreate"),
path('employer/job/<int:pk>/delete/',EmployerJobDeleteView.as_view(), name="employerjobdelete"),
path('employer/job/<int:pk>/update/',EmployerJobUpdateView.as_view(), name="employerjobupdate"),
path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/<int:pk>/detail/",EmployerOwnDetailView.as_view(),name="employerowndetail"),

path("employer/category/",EmployerCategoryView.as_view(),name="employercategory"),
path("employer/category/create/",EmployerCategoryCreateView.as_view(),name="employercategorycreate"),
path('employer/category/<int:pk>/delete/',EmployerCategoryDeleteView.as_view(), name="employercategorydelete"),
path('employer/category/<int:pk>/update/',EmployerCategoryUpdateView.as_view(), name="employercategoryupdate"),
path("employer/logout/",EmployerLogoutView.as_view(),name="employerlogout"),





path("search/",EmployerSearchView.as_view(),name="employersearch"),

path("employer/home/jobs/list/",EmployerHomeJobListView.as_view(),name="employerhomejoblist"),
path("employer/category/list/",EmployerCategoryListView.as_view(),name="employercategorylist"),
path("employer/category/<int:pk>/detail/",EmployerCategoryDetailView.as_view(),name="employercategorydetail"),
path("employer/profile/<int:pk>/detail/",EmployerprofileDetailView.as_view(),name="employerprofile"),
path("employer/jobseeker/<int:pk>/detail/",EmployerJobseekerDetailView.as_view(),name="employerjobseeker"),
path("jobseeker/jobseekerapplied/", JobSeekerJobappliedmessagelView.as_view(), name="jobmessage"),











# jobseeker
path("jobseeker/home/",JobSeekerHomeView.as_view(),name="jobseekerhome"),
path("jobseeker/profile/list/",JobSeekerProfileListView.as_view(),name="jobseekerprofilelist"),

path("jobseeker/profile/detail/",JobSeekerProfileDetailView.as_view(),name="jobseekerprofiledetail"),
path("profile/detail/",ProfileDetailView.as_view(),name="profiledetail"),
path("jobseeker/profile/<int:pk>/update/",JobSeekerProfileUpdateView.as_view(),name="jobseekerprofileupdate"),
path("jobseeker/profile/<int:pk>/delete/",JobSeekerProfileDeleteView.as_view(),name="jobseekerprofiledelete"),


path("job/<int:pk>/apply",JobSeekerJobApplyView.as_view(),name="jobseekerjobapply"),


path("jobseeker/job/list",J_ApplyListView.as_view(),name="jobseekerjoblist"),
path("jobseeker/job/<int:pk>/detail",JobSeekerJobDetailView.as_view(),name="jobseekerjobdetail"),

#contact
path("contact/create/",ContactCreateView.as_view(),name="contactcreate"),
path("contact/list/",ContactListView.as_view(),name="contactlist"),
path("contact/<int:pk>/update/",ContactUpdateView.as_view(),name="contactupdate"),


#about
path("about/create/",AboutCreateView.as_view(),name="aboutcreate"),
path("about/list/",AboutListView.as_view(),name="aboutlist"),
path("about/<int:pk>/update/",AboutUpdateView.as_view(),name="aboutupdate"),




]

quickproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include("quickapp.urls")),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

quickapp/forms.py
from django import forms
from .models import*


class LoginForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	password=forms.CharField(widget=forms.PasswordInput())


class SlideShowForm(forms.ModelForm):
    class Meta:
        model = SlideShow
        fields = ['title', 'caption', 'image']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Title'
            }),
            'caption': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Main Text here'
            }),
            'image': forms.FileInput(attrs={
                'class': 'form-control'
            }),
        }


class JregisterForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'username',
                }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'password'
                }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'confirm password'
                }))

    class Meta:
        model = JobSeeker
        fields = ["username", "password", "confirm_password","skill", "full_name",
                  "mobile", "email", "cv", "address", "image", "dob", "education"]
        widgets = {
            'full_name': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Full Name'
            }),
            'skill': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Skill'
            }),
            'address': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Address'
            }),
            'dob': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Dob'
            }),
            'mobile': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Mobile Number'
            }),
            'image': forms.FileInput(attrs={
                'class': 'login-form-rec'
            }),
            'email': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Email'
            }),
            'education': forms.Select(attrs={
                'class': 'frm-field required',
                'id' : 'country13',
                'placeholder': 'Education'
            }),
            'cv' : forms.FileInput(attrs={
            	'class': 'login-form-rec',
            	'placeholder': 'cv'
            	}),
   
        }
    def clean_username(self):
        uname = self.cleaned_data["username"]
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError("This username is already taken")
        return uname



class EregisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'login-form-rec',
        'placeholder': 'username'
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'login-form-rec',
        'placeholder': 'password'
        }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'login-form-rec',
        'placeholder': 'confirm password'
        }))

    class Meta:
        model = Employer
        fields = ["username", "password", "confirm_password","company_name", "full_name",
                  "company_logo", "company_photo", "mobile", "email", "website", "address",
                  "image", "location", "estb_date","about"]
        widgets = {
            'full_name': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Owner Full Name'
            }),
            'company_name': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'company name'
            }),
            'address': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Address'
            }),
            'company_logo': forms.FileInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Company Logo'
            }),
            'company_photo': forms.FileInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Company Photo'
            }),
            'mobile': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Mobile Number'
            }),
            'phone': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Phone Number'
            }),
            'image': forms.FileInput(attrs={
                'class': 'login-form-rec'
            }),
            'email': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Email'
            }),
            'website': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Company website'
            }),
            'location': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Campany Location'
            }),
            'estb_date': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'Statblished Date'
            }),
            'about' : forms.Textarea(attrs={
            	'class': 'login-form-rec',
            	'placeholder': 'About'
            	}),   
        }

    def clean_username(self):
        uname = self.cleaned_data["username"]
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError("This username is already taken")

        return uname

class AdminJobCategoryForm(forms.ModelForm):
	class Meta:
		model=Category
		fields=["title","image"]


# project done by susan dulal
class EmployerJobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ["employer"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'




class EmployerCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields=["title","image",]






# Rupak

class JobApplyForm(forms.ModelForm):
	class Meta:
		model=Application
		fields=["cover_letter"]

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields = ["email","telephone","image","location"]

        widgets = {
            'telephone': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'telephone number'
            }),

            'email': forms.EmailInput(attrs={
            'class': 'login-form-rec',
            'placeholder': 'eg:abc@gmail.com'
            }),

            'image': forms.FileInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'image '
            }),

            'location': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'location'
            }),
        }

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ["detail","image"]

        widgets = {
            'detail': forms.TextInput(attrs={
                'class': 'login-form-rec',
                'placeholder': 'detail'
            }),
            'image': forms.FileInput(attrs={
                'class': 'login-form-rec'
                }),
            }

templates/clienttemplates/clientcategorydetail.html
{% extends 'clienttemplates/clientbase.html' %}
{% block category %}active {% endblock %}

{% block content %}
	<div class="inner_page_agile">
		<h3>Jobs</h3>
		<p>Add Some Short Description</p>
	</div>
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">
			<ul class="short_w3ls"_w3ls>
				<li><a href="/">Home</a><span>|</span></li>
				<li>Jobs</li>
			</ul>
		</div>
	</div>
<!-- top joblist-->
		<div class="inner_content_info_agileits">
		<div class="container">
			<div class="inner_sec_grids_info_w3ls">
						<div class="col-md-8 job_info_left">
					<div class="but_list">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
							<ul id="myTab" class="nav nav-tabs" role="tablist">
								<li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">	<h3>Jobs under {{ categoryobject.title }} category</h3></a></li>							
							</ul>
							<div id="myTabContent" class="tab-content">
								<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
								{% for job in categoryobject.job_set.all %}
									{% cycle '<div class="tab_grid">' '' %}
											<div class="col-sm-2 loc_1">
												<a href="{% url 'quickapp:jobdetail' job.id %}"><img src="{{job.employer.company_logo.url}}" alt=""></a>
											</div>
											<div class="col-sm-4">
												<div class="location_box1">
													<p><span class="m_2"><a href="{% url 'quickapp:jobdetail' job.id %}">{{job.title}} </a></span><br>
														<a href="{% url 'quickapp:jobdetail' job.id %}">{{job.employer.company_name}}</a>
														</p>
													</div>
											</div>										
											{% if forloop.counter|divisibleby:2 %}		
											<div class="clearfix"> </div>
									</div>	{% endif %}									
								{% endfor %}
									{% resetcycle %}			
								</div>			
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 job_info_right">
				<div class="widget_search">
					<h5 class="widget-title">Search</h5>
					<div class="widget-content">
						<form action="/results/" method="GET">
							<input type="text" class="form-control jb_2" placeholder="Enter Keyword(s)" name="searchkey" value="{{request.GET.searchkey}}" >
							<input type="submit" value="Search">
						</form>
					</div>
				</div>
				<div class="col_3 permit">
					<h3>Jobs by Category</h3>
					<ul class="list_2">
						{% for category in categorylist %}
						{% for jobs in category.job_set.all %}
							<li><a href="{% url 'quickapp:clientcategorydetail' category.id %}">
							{% if forloop.last %}
							{{category.title}} 
							({{forloop.counter}})
							{% endif %}
							</a>
							</li>
						{% endfor %}
						
						{% endfor %}
					</ul>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<!--//top joblist -->
{% endblock %}

templates/clienttemplates/clientemployerregister.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block content %}
		<!-- banner -->
	<div class="inner_page_agile">
		<h3>Register</h3>
		<p>Add Some Short Description</p>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="index.html">Home</a><span>|</span></li>
				<li>Employer Register</li>
			</ul>
		</div>
	</div>
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info_agileits">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle three">Register Now </h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="signin-form">
					<div class="login-form-rec">
						<form method="POST" enctype="multipart/form-data">
							{% csrf_token %}
<!-- 							{{form.as_p}}
 -->						{{form.username}}
 							<span id="id_message"></span>
							{{form.password}}
							{{form.confirm_password}}
							<span id="password_massege"></span>
							{{form.full_name}}
							{{form.company_name}}
							{{form.phone}}
							{{form.mobile}}
							{{form.email}}
							{{form.website}}
							{{form.address}}
							{{form.about}}
							{{form.estb_date}}
							{{form.location}}
							<input type="submit" value="Register" id="save_button">
						</form>
					</div>
					<p class="reg"><a href="#"> By clicking register, I agree to your terms</a></p>

				</div>
			</div>
		</div>
	</div>

{% endblock %}

  {% block js %}
<script type="text/javascript">
	$('#id_password, #id_confirm_password').on('keyup', function () {
		if ($('#id_password').val() == ""){
			 $('#password_massege').html('');
		}
		else if($('#id_confirm_password').val( ) == ""){

			$('#password_massege').html('');
		}else{
	  if ($('#id_password').val() == $('#id_confirm_password').val()) {
	    $('#password_massege').html(' Password Matching').css('color', 'green');
	  } else 
	    $('#password_massege').html(' Password Not Matching').css('color', 'red');
	   }


	});
</script>
<script type="text/javascript">
	$("#id_username").on('keyup',function(){
		var uname = $(this).val().trim();
		if($("#id_username").val() ==""){
			$('#id_message').text("");
		}
		else{
		$.ajax({
			method:'get',
			url : '/username-checker/',
			data:{
				username:uname
			},
			success: function(data){
				$('#id_message').text(data.message).css('color',data.color);
				if(data.color=='red'){
					$('#save_button').attr('disabled',true)
				}
				else
				{
					$('#save_button').attr('disabled',false)
				}
			}
		})
	}
	})

</script>
{% endblock %}

templates/clienttemplates/clientevent.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

<!-- banner -->
	<div class="inner_page_agile">
		<h3>Events</h3>
		<p>Add Some Short Description</p>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="{% url 'quickapp:clienthome' %}">Home</a><span>|</span></li>
				<li>Events</li>
			</ul>
		</div>
	</div>
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info_agileits">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">Our Events</h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-4 blog-grid one">
					<a href="single.html"><img src="{% static 'clientstatic/images/e6.jpg' %}" alt=""></a>
					<div class="events_info">
						<h5>Oct 12,2017</h5>
						<h4><a href="single.html">Talent Programmes</a></h4>
						<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>

					</div>
				</div>
				<div class="col-md-4 blog-grid one">
					<a href="single.html"><img src="{% static 'clientstatic/images/e5.jpg' %}" alt=""></a>
					<div class="events_info">
						<h5>Oct 26,2017</h5>
						<h4><a href="single.html">Talent Programmes</a></h4>
						<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
					</div>
				</div>
				<div class="col-md-4 blog-grid one lost">
					<a href="single.html"><img src="{% static 'clientstatic/images/e4.jpg' %}" alt=""></a>
					<div class="events_info">
						<h5>Nov 06,2017</h5>
						<h4><a href="single.html">Talent Programmes</a></h4>
						<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
					</div>
				</div>
				<div class="col-md-4 blog-grid">
					<a href="single.html"><img src="{% static 'clientstatic/images/e1.jpg' %}" alt=""></a>
					<div class="events_info">
						<h5>Oct 12,2017</h5>
						<h4><a href="single.html">Talent Programmes</a></h4>
						<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>

					</div>
				</div>
				<div class="col-md-4 blog-grid">
					<a href="single.html"><img src="{% static 'clientstatic/images/e2.jpg' %}" alt=""></a>
					<div class="events_info">
						<h5>Oct 26,2017</h5>
						<h4><a href="single.html">Talent Programmes</a></h4>
						<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
					</div>
				</div>
				<div class="col-md-4 blog-grid lost">
					<a href="single.html"><img src="{% static 'clientstatic/images/e3.jpg' %}" alt=""></a>
					<div class="events_info">
						<h5>Nov 06,2017</h5>
						<h4><a href="single.html">Talent Programmes</a></h4>
						<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
					</div>
				</div>
				<div class="clearfix"></div>

			</div>

		</div>
	</div>
	<!-- //mid-services -->

	<!-- //inner_content -->

{% endblock %}

templates/clienttemplates/clientjobdetails.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block content %}
<div class="inner_content_info_agileits">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">Job Details</h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-8 job_info_left">
					<div class="single-left1">
						<img src="{{jobD.employer.company_photo.url}}" alt=" " class="img-responsive" />
						
						
						<!-- company detail	-->		
						<div class="comments-grid" style="background: cyan;padding:15px;margin-top: 0">
							<div class="comments-grid-left" style="padding-top:15px;margin-right: 15px;">
								<img src="{{jobD.employer.company_logo.url}}" alt=" " class="img-responsive">
							</div><h3>{{jobD.employer.company_name}}</h3>
									<div class="comments-grid-right" style="width: 100%">
									<p>{{jobD.employer.about|truncatechars:300}}</p>
										<h5><a href="#">View Company Details</a></h5>
								</div>
								<div class="clearfix"> </div>
							</div>
						<div class="col_3 experience">
						<h3 style="margin:0">{{jobD.title}}</h3><hr>

						<h4 style="margin:5px">Job detail Information</h4>
						<table class="table">
							<tbody>
								<tr class="unread checked">
									<td class="hidden-xs">
										Job Category :
									</td>
									<td>
										{{jobD.category}}
									</td>
								</tr>
								<tr class="unread checked">
									<td class="hidden-xs">
										No of Vacancie(s) :
									</td>
									<td>
										{{jobD.no_of_post}}
									</td>
								</tr>
								<tr class="unread checked">
									<td class="hidden-xs">
										Job Level :
									</td>
									<td>
										{{jobD.level}}
									</td>
								</tr>
								<tr class="unread checked">
									<td class="hidden-xs">
										Required Experience :
									</td>
									<td>
										{{jobD.experience}}
									</td>
								</tr>
								<tr class="unread checked">
									<td class="hidden-xs">
										Offered Salary :
									</td>
									<td>
										{{jobD.salary}}
									</td>
								</tr>
								<tr class="unread checked">
									<td class="hidden-xs">
										Totol View :
									</td>
									<td>
										{{jobD.view_count}}
									</td>
								</tr>
								<tr class="unread checked">
									<td class="hidden-xs">
										Apply Before(Deadline) :
									</td>
									<td>
										{{jobD.deadline}}
									</td>
								</tr>
							</tbody>
						</table><hr>
						<h4>Job Description</h4><hr>
						<p>{{jobD.description|safe}}</p>
						<div class="grid_3 grid_5 w3">
							<a href="{% url 'quickapp:jobseekerjobapply' jobD.id %}"><span class="label label-success" style="font-size: 23px;padding: 5px 15px;"> Apply Now</span></a>
						</div>
					</div>
					</div>
				</div>
				<div class="col-md-4 job_info_right">
				<div class="widget_search">
					<h5 class="widget-title">Search</h5>
					<div class="widget-content">
						<form action="/results/" method="GET">
							<input type="text" class="form-control jb_2" placeholder="Enter Keyword(s)" name="searchkey" value="{{request.GET.searchkey}}" >
							<input type="submit" value="Search">
						</form>
					</div>
				</div>
				<div class="col_3 permit">
					<h3>Jobs by Category</h3>
					<ul class="list_2">
						{% for category in categorylist %}
						{% for jobs in category.job_set.all %}
							<li><a href="{% url 'quickapp:clientcategorydetail' category.id %}">
							{% if forloop.last %}
							{{category.title}} 
							({{forloop.counter}})
							{% endif %}
							</a>
							</li>
						{% endfor %}
						
						{% endfor %}
					</ul>
				</div>			
			<div class="clearfix"></div>
				<div class="col_3 experience">
					<h3>New Jobs</h3>
					<table class="table">
						<tbody>
							<tr class="unread checked">
								<td class="hidden-xs">
								{% for pjob in pjobs %}
									<div class="col-sm-4 loc_1">
												<a href="{% url 'quickapp:jobdetail' pjob.id %}"><img src="{{pjob.employer.company_logo.url}}" alt=""></a>
											</div>
											<div class="col-sm-8">
												<div class="location_box1">
													<p><span class="m_2"><a href="{% url 'quickapp:jobdetail' pjob.id %}">{{pjob.title}} </a></span><br>
														<a href="{% url 'quickapp:jobdetail' pjob.id %}">{{pjob.employer.company_name}}</a>
														</p>
													</div>
											</div>								<div class="clearfix"> </div>
								{% endfor %}
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
{% endblock %}