quickapp/urls.py
from django.urls import path
from .views import*

app_name="quickapp"
urlpatterns=[


path('login/',LoginView.as_view(),name="login"),

path("logout/",LogoutView.as_view(),name="logout"),


#client
path('',ClientHomeView.as_view(),name="clienthome"),
path('contact/',ClientContactView.as_view(),name="clientcontact"),
path('about/',ClientAboutView.as_view(),name="clientabout"),
path('profession/',ClientProfession.as_view(),name="clientprofession"),
path('events/',ClientEventView.as_view(),name="clientevent"),
path('employerregister/', EregisterView.as_view(),name="employerregister"),
path('jobseekerregister/', JregisterView.as_view(),name="jobseekerregister"),
path('username-checker/', IdCheckerView.as_view(),name="idchecker"),
path('job/<int:pk>/detail', ClientJobDetailView.as_view(),name="jobdetail"),
path("results/", ClientSearchView.as_view(), name="search"),
path("category/<int:pk>/list/", ClientCategoryDetailView.as_view(), name="clientcategorydetail"),





#admin
path("admin/home/",AdminHomeView.as_view(),name="adminhome"),
path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),
path("admin/jobcategory/<int:pk>/detail/",AdminJobCategoryDetailView.as_view(),name="adminjobcategorydetail"),
path("admin/jobcategory/create/",AdminJobCategoryCreateView.as_view(),name="adminjobcategorycreate"),
path("admin/jobcategory/<int:pk>/update/",AdminJobCategoryUpdateView.as_view(),name="adminjobcategoryupdate"),
path("admin/jobcategory/<int:pk>/delete/",AdminJobCategoryDeleteView.as_view(),name="adminjobcategorydelete"),
path("admin/job/list/",AdminJobListView.as_view(),name="adminjoblist"),
path("admin/job/<int:pk>/delete/",AdminJobDeleteView.as_view(),name="adminjobdelete"),
path("admin/job/<int:pk>/detail/",AdminJobDetailView.as_view(),name="adminjobdetail"),
#path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),


path("admin/profile/",AdminProfileView.as_view(),name="adminprofile"),

path("admin/employer/list/",EmployerListView.as_view(),name="employerlist"),
path("admin/employers/list/",AdminEmployerListView.as_view(),name="adminemployerlist"),
path("admin/employer/<int:pk>/detail/",AdminEmployerDetailView.as_view(),name="adminemployerdetail"),
path("admin/employer/<int:pk>/delete/",AdminEmployerDeleteView.as_view(),name="adminemployerdelete"),

path("admin/jobseeker/list/",AdminJobSeekerListView.as_view(),name="adminjobseekerlist"),
path("admin/jobseeker/<int:pk>/detail",AdminJobSeekerDetailView.as_view(),name="adminjobseekerdetail"),
path("admin/jobseeker/<int:pk>/delete/",AdminJobSeekerDeleteView.as_view(),name="adminjobseekerdelete"),


path("admin/slideshow/list/", AdminSlideShowListView.as_view(), name='adminslideshowlist'),
path("admin/slideshow/create/", AdminSlideShowCreateView.as_view(), name='adminslideshowcreate'),
path("admin/slideshow/<int:pk>/update/", AdminSlideShowUpdateView.as_view(), name='adminslideshowupdate'),
path("admin/slideshow/<int:pk>/delete/", AdminSlideShowDeleteView.as_view(), name='adminslideshowdelete'),


#employer
path("employer/home/",EmployerHomeView.as_view(),name="employerhome"),
path("employer/dashboard/",EmployerDashBoardView.as_view(),name="employerdashboard"),
path("employer/jobs/create/",EmployerJobCreateView.as_view(),name="employerjobcreate"),
path('employer/job/<int:pk>/delete/',EmployerJobDeleteView.as_view(), name="employerjobdelete"),
path('employer/job/<int:pk>/update/',EmployerJobUpdateView.as_view(), name="employerjobupdate"),
path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/<int:pk>/detail/",EmployerOwnDetailView.as_view(),name="employerowndetail"),

path("employer/category/",EmployerCategoryView.as_view(),name="employercategory"),
path("employer/category/create/",EmployerCategoryCreateView.as_view(),name="employercategorycreate"),
path('employer/category/<int:pk>/delete/',EmployerCategoryDeleteView.as_view(), name="employercategorydelete"),
path('employer/category/<int:pk>/update/',EmployerCategoryUpdateView.as_view(), name="employercategoryupdate"),
path("employer/logout/",EmployerLogoutView.as_view(),name="employerlogout"),





path("search/",EmployerSearchView.as_view(),name="employersearch"),

path("employer/home/jobs/list/",EmployerHomeJobListView.as_view(),name="employerhomejoblist"),
path("employer/category/list/",EmployerCategoryListView.as_view(),name="employercategorylist"),
path("employer/category/<int:pk>/detail/",EmployerCategoryDetailView.as_view(),name="employercategorydetail"),
path("employer/profile/<int:pk>/detail/",EmployerprofileDetailView.as_view(),name="employerprofile"),
path("employer/jobseeker/<int:pk>/detail/",EmployerJobseekerDetailView.as_view(),name="employerjobseeker"),
path("jobseeker/jobseekerapplied/", JobSeekerJobappliedmessagelView.as_view(), name="jobmessage"),











# jobseeker
path("jobseeker/home/",JobSeekerHomeView.as_view(),name="jobseekerhome"),
path("jobseeker/profile/list/",JobSeekerProfileListView.as_view(),name="jobseekerprofilelist"),

path("jobseeker/profile/detail/",JobSeekerProfileDetailView.as_view(),name="jobseekerprofiledetail"),
path("profile/detail/",ProfileDetailView.as_view(),name="profiledetail"),
path("jobseeker/profile/<int:pk>/update/",JobSeekerProfileUpdateView.as_view(),name="jobseekerprofileupdate"),
path("jobseeker/profile/<int:pk>/delete/",JobSeekerProfileDeleteView.as_view(),name="jobseekerprofiledelete"),


path("job/<int:pk>/apply",JobSeekerJobApplyView.as_view(),name="jobseekerjobapply"),


path("jobseeker/job/list",J_ApplyListView.as_view(),name="jobseekerjoblist"),
path("jobseeker/job/<int:pk>/detail",JobSeekerJobDetailView.as_view(),name="jobseekerjobdetail"),

#contact
path("contact/create/",ContactCreateView.as_view(),name="contactcreate"),
path("contact/list/",ContactListView.as_view(),name="contactlist"),
path("contact/<int:pk>/update/",ContactUpdateView.as_view(),name="contactupdate"),


#about
path("about/create/",AboutCreateView.as_view(),name="aboutcreate"),
path("about/list/",AboutListView.as_view(),name="aboutlist"),
path("about/<int:pk>/update/",AboutUpdateView.as_view(),name="aboutupdate"),




]

quickproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include("quickapp.urls")),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/admintemplates/Adminjobdelete.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<div class="bs-example2">
	<div class="modal-dialog">
		<div class="modal-content">
				<div class="modal-header">
					<a href="{% url 'quickapp:adminjoblist' %}">
						<div class="close" data-dismiss="modal" aria-hidden="true">×</div>
					</a>
					<h2 class="modal-title">Delete Confirmation</h2>
				</div>				
				<div class="modal-body">
					<p>Are sure to delete '{{object.title}}'?</p>
				</div>
				<div class="modal-footer">
					<form method="POST" action="{% url 'quickapp:adminjobdelete' object.id %}">	
	  					{% csrf_token %}
	  					<a href="{% url 'quickapp:adminjoblist' %}" class="btn btn-default close" data-dismiss="modal">Cancel</a>
						<button class="btn btn-primary">Yes</button>
					</form>
				</div>
		</div>
	</div>
</div>
{% endblock %}

templates/admintemplates/aboutlist.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block content %}

	<!-- banner -->
	<div class="inner_page_agile">
		<h3>Know</h3>
		<p>About Us</p>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="{% url 'quickapp:adminhome' %}">Home</a><span>|</span></li>
				<li>About</li>
			</ul>
		</div>
	</div>
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info_agileits">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">What We Are </h3>
			</div>

			{% for ab_list in aboutlist %}

			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-6 banner_bottom_left">
					<h5><p>{{ab_list.detail}}</p></h5>

<!-- 					<ul class="some_agile_facts">
						<li><span class="fa fa-briefcase" aria-hidden="true"></span><label>80</label> Corporate Programs</li>
						<li><span class="fa fa-graduation-cap" aria-hidden="true"></span><label>49</label> Training Courses</li>
						<li><span class="fa fa-user" aria-hidden="true"></span><label>88</label> Strategic Partners</li>
						<li><span class="fa fa-line-chart" aria-hidden="true"></span><label>436</label> Companies We Helped</li>
					</ul> -->
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-6 banner_bottom_right">
					<div class="agileits_w3layouts_banner_bottom_grid">
						<img src="{{ab_list.image.url}}" alt=" " class="img-responsive" />
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>




{% endfor %}

{% endblock %}

templates/admintemplates/adminbase.html
{% load static %}
     
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>Augment an Admin Panel Category Flat Bootstrap Responsive Web Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Augment Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href="{% static 'adminstatic/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="{% static 'adminstatic/css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="{% static 'adminstatic/css/font-awesome.css' %}" rel="stylesheet"> 
<!-- jQuery -->
<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css'>
<!-- lined-icons -->
<link rel="stylesheet" href="{% static 'adminstatic/css/icon-font.min.css' %}" type='text/css' />
<!-- //lined-icons -->
<script src="{% static 'adminstatic/js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'adminstatic/js/amcharts.js' %}"></script>	
<script src="{% static 'adminstatic/js/serial.js' %}"></script>	
<script src="{% static 'adminstatic/js/light.js' %}"></script>	
<script src="{% static 'adminstatic/js/radar.js' %}"></script>	
<link href="{% static 'adminstatic/css/barChart.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'adminstatic/css/fabochart.css' %}" rel='stylesheet' type='text/css' />
<!--clock init-->
<script src="{% static 'adminstatic/js/css3clock.js' %}"></script>
<!--Easy Pie Chart-->
<!--skycons-icons-->
<script src="{% static 'adminstatic/js/skycons.js' %}"></script>

<script src="{% static 'adminstatic/js/jquery.easydropdown.js' %}"></script>

<!--//skycons-icons-->
</head> 
<body>
   <div class="page-container">
   <!--/content-inner-->
	<div class="left-content">
	   <div class="inner-content">
		<!-- header-starts -->
			<div class="header-section">
						<!--menu-right-->
							<!--/profile_details-->
								<div class="profile_details_left">
									<ul class="nofitications-dropdown">
									       <li class="dropdown note">
											<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i>update</i></a>

												
													<ul class="dropdown-menu two first">

														<li><a href="#">
														  
														   <div >
															<h4><a href="/about/1/update/">About</a></h4>
															<div class="clearfix"></div>	
														 </a></li>
														 <li class="odd"><a href="#">
															
														   <div class="notification_desc">
															<h4><a href="/contact/1/update/">Contact</a></h4>
															
															</div>
														  <div class="clearfix"></div>	
														 </a></li>
														
													</ul>
										</li>

																	Logged in as : {{request.user.username}}		   							   		
							<div class="clearfix"></div>	
								</ul>
							</div>
							<div class="clearfix"></div>	
							<!--//profile_details-->
						</div>
						<!--//menu-right-->
					<div class="clearfix"></div>
				</div>
					<!-- //header-ends -->
						<div class="outter-wp">


						{% block content %}

						{% endblock %}
				</div>


	{% block js %}
     

    {% endblock %}

	
	<!-- js -->
	<!--/sidebar-menu-->
				<div class="sidebar-menu">
					<header class="logo">
					<a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a> <a href="{% url 'quickapp:adminhome' %}"> <span id="logo"> <h1>Quickjob	</h1></span> 
					<!--<img id="logo" src="" alt="Logo"/>--> 
				  </a> 
				</header>
			<div style="border-top:1px solid rgba(69, 74, 84, 0.7)"></div>
			<!--/down-->
							<div class="down">	
									  <a href="{% url 'quickapp:adminhome' %}"><img src="{% static 'adminstatic/images/admin.jpg' %}"></a>
									  <a href="{% url 'quickapp:adminhome' %}"><span class=" name-caret">Prabin Chaudhary</span></a>
									 <p>System Administrator in Quickjob</p>
									<ul>
									<li><a class="tooltips" href="{% url 'quickapp:adminprofile' %}"><span>Profile</span><i class="lnr lnr-user"></i></a></li>
										<li><a class="tooltips" href="{% url 'quickapp:adminhome' %}"><span>Settings</span><i class="lnr lnr-cog"></i></a></li>
										<li><a class="tooltips" href="{% url 'quickapp:logout' %}"><span>Log out</span><i class="lnr lnr-power-switch"></i></a></li>
										</ul>
									</div>
							   <!--//down-->
                           <div class="menu">
									<ul id="menu" >
										<li class="{% block createcategory %} {% endblock %}"><a href="{% url 'quickapp:adminjobcategorycreate' %}"><i class="lnr lnr-pencil"></i> <span>create category</span></a></li>
										<li class="{% block categorylist %} {% endblock %}"><a href="{% url 'quickapp:adminjobcategorylist' %}"><i class="lnr lnr-pencil"></i> <span>category list</span></a></li>
										<li class="{% block employerlist %} {% endblock %}"><a href="{% url 'quickapp:adminemployerlist' %}"><i class="lnr lnr-pencil"></i> <span>Employer list</span></a></li>
										<li class="{% block adminjobseekerlist %} {% endblock %}"><a href="{% url 'quickapp:adminjobseekerlist' %}"><i class="lnr lnr-pencil"></i> <span>Jobseeker list</span></a></li>
										<li class=""><a href="{% url 'quickapp:adminjoblist' %}"><i class="lnr lnr-pencil"></i> <span>Jobs list</span></a></li>

										<!-- <li><a href="index.html"><i class="fa fa-tachometer"></i> <span>Dashboard</span></a></li>
										 <li id="menu-academico" ><a href="#"><i class="fa fa-table"></i> <span> Tabs &amp; Panels</span> <span class="fa fa-angle-right" style="float: right"></span></a>
										   <ul id="menu-academico-sub" >
											<li id="menu-academico-avaliacoes" ><a href="tabs.html"> Tabs &amp; Panels</a></li>
											<li id="menu-academico-boletim" ><a href="widget.html">Widgets</a></li>
											<li id="menu-academico-avaliacoes" ><a href="calender.html">Calendar</a></li>
											
										  </ul>
										</li>
										 <li id="menu-academico" ><a href="#"><i class="fa fa-file-text-o"></i> <span>Ui Elements</span> <span class="fa fa-angle-right" style="float: right"></span></a>
											 <ul id="menu-academico-sub" >
												<li id="menu-academico-avaliacoes" ><a href="forms.html">Forms</a></li>
												<li id="menu-academico-boletim" ><a href="validation.html">Validation Forms</a></li>
												<li id="menu-academico-boletim" ><a href="table.html">Tables</a></li>
												<li id="menu-academico-boletim" ><a href="buttons.html">Buttons</a></li>
											  </ul>
										 </li>
									<li><a href="typography.html"><i class="lnr lnr-pencil"></i> <span>Typography</span></a></li>
									<li id="menu-academico" ><a href="#"><i class="lnr lnr-book"></i> <span>Pages</span> <span class="fa fa-angle-right" style="float: right"></span></a>
										  <ul id="menu-academico-sub" >
										    <li id="menu-academico-avaliacoes" ><a href="login.html">Login</a></li>
										    <li id="menu-academico-boletim" ><a href="register.html">Register</a></li>
											<li id="menu-academico-boletim" ><a href="404.html">404</a></li>
											<li id="menu-academico-boletim" ><a href="sign.html">Sign up</a></li>
											<li id="menu-academico-boletim" ><a href="profile.html">Profile</a></li>
										  </ul>
									 </li>
									 <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Mail Box</span><span class="fa fa-angle-right" style="float: right"></span></a>
									   <ul>
										<li><a href="inbox.html"><i class="fa fa-inbox"></i> Inbox</a></li>
										<li><a href="compose.html"><i class="fa fa-pencil-square-o"></i> Compose Mail</a></li>
										<li><a href="editor.html"><span class="lnr lnr-highlight"></span> Editors Page</a></li>
									
									  </ul>
									</li>
							        <li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span>Components</span> <span class="fa fa-angle-right" style="float: right"></span></a>
										 <ul id="menu-academico-sub" >
											<li id="menu-academico-avaliacoes" ><a href="grids.html">Grids</a></li>
											<li id="menu-academico-boletim" ><a href="media.html">Media Objects</a></li>

										  </ul>
									 </li>
									<li><a href="chart.html"><i class="lnr lnr-chart-bars"></i> <span>Charts</span> <span class="fa fa-angle-right" style="float: right"></span></a>
									  <ul>
										<li><a href="map.html"><i class="lnr lnr-map"></i> Maps</a></li>
										<li><a href="graph.html"><i class="lnr lnr-apartment"></i> Graph Visualization</a></li>
									</ul>
									</li>
									<li id="menu-comunicacao" ><a href="#"><i class="fa fa-smile-o"></i> <span>More</span><span class="fa fa-angle-double-right" style="float: right"></span></a>
									  <ul id="menu-comunicacao-sub" >
										<li id="menu-mensagens" style="width:120px" ><a href="project.html">Projects <i class="fa fa-angle-right" style="float: right; margin-right: -8px; margin-top: 2px;"></i></a>
										  <ul id="menu-mensagens-sub" >
											<li id="menu-mensagens-enviadas" style="width:130px" ><a href="ribbon.html">Ribbons</a></li>
											<li id="menu-mensagens-recebidas"  style="width:130px"><a href="blank.html">Blank</a></li>
										  </ul>
										</li>
										<li id="menu-arquivos" ><a href="500.html">500</a></li>
									  </ul>
									</li> -->
								  </ul>
								</div>
							  </div>
							  <div class="clearfix"></div>		
							</div>
							<script>
							var toggle = true;
										
							$(".sidebar-icon").click(function() {                
							  if (toggle)
							  {
								$(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
								$("#menu span").css({"position":"absolute"});
							  }
							  else
							  {
								$(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
								setTimeout(function() {
								  $("#menu span").css({"position":"relative"});
								}, 400);
							  }
											
											toggle = !toggle;
										});
							</script>
<!--js -->
<link rel="stylesheet" href="{% static 'adminstatic/css/vroom.css' %}">
<script type="text/javascript" src="{% static 'adminstatic/js/vroom.js' %}"></script>
<script type="text/javascript" src="{% static 'adminstatic/js/TweenLite.min.js' %}"></script>
<script type="text/javascript" src="{% static 'adminstatic/js/CSSPlugin.min.js' %}"></script>
<script src="{% static 'adminstatic/js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'adminstatic/js/scripts.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
   <script src="{% static 'adminstatic/js/bootstrap.min.js' %}"></script>
    <!--footer section start-->
										<footer>
										   <p>&copy 2019 Quickjob . All Rights Reserved | Design by <a href="#" target="_blank">MitJiuGroup.</a></p>
										</footer>
									<!--footer section end-->
</body>

</html>

templates/admintemplates/adminemployerdelete.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3>Delete Employer</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<h4>Are sure to delete this category</h4>
			<button class="btn btn-outline-success">Yes</button>
			<a href="{% url 'quickapp:adminemployerlist' %}">No</a>
		</form>
	</div>
</div>

{% endblock %}

templates/admintemplates/adminemployerdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block content %}

<div class="row">
	<div class="col-md-8">
		<h3 class="text-center">Employer Detail</h3>
		<table class="table table-striped">
			<tr>
				<th>Full Name</th>
				<td>{{adminempdetail.full_name}}</td>
			</tr>
			<tr>
				<th>Company Name</th>
				<td>{{adminempdetail.company_name}}</td>
			</tr>
			<tr>
				<th>Company Logo</th>
				<td>{{adminempdetail.company_logo}}</td>
			</tr>
			<tr>
				<th>Company Photo</th>
				<td>{{adminempdetail.company_photo}}</td>
			</tr>
			<tr>
				<th>Address</th>
				<td>{{adminempdetail.address}}</td>
			</tr>
			<tr>
				<th>Mobile</th>
				<td>{{adminempdetail.mobile}}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{adminempdetail.email}}</td>
			</tr>
			<tr>
				<th>Website</th>
				<td>{{adminempdetail.website}}</td>
			</tr>
			<tr>
				<th>Location</th>
				<td>{{adminempdetail.location}}</td>
			</tr>
			<tr>
				<th>About</th>
				<td>{{adminempdetail.about}}</td>
			</tr>
			<tr>
			</tr>
		</table>
	</div>
</div>



<div class="error-btn">
 <a class="read fourth" href="{% url 'quickapp:adminhome' %}">Return to Home</a>
</div>

{% endblock %}

templates/admintemplates/adminemployerlist.html
{% extends 'admintemplates/adminbase.html' %}
{% block employerlist %} active {% endblock %}

{% load static %}

{% block content %}
<h3 class="text-center">Employer list</h3>

<div class="row">
	<div class="col-md-12">
	    <!-- <h3>This is {{full_name.full_name}}</h3> -->
	    <table class="table table-bordered">
	    	<head>
	    		<tr>
	    			<th>SN</th>
	    			<th>Full Name</th>
	    			<th>Company Name</th>
	    			<th>Mobile</th>
	    			<th>Email</th>
	    			<th>Action</th>


	    		</tr>
	    	</head>
	    	<tbody>
	    		{% for emp in adminemployerlists %}
	    		<tr>
	    			<td>{{forloop.counter}}</td>
	    			<td><a href="{% url 'quickapp:adminemployerdetail' emp.id %}">{{emp.full_name}}</a></td>
		   			<td>{{emp.company_name}}</td> 
	    			<td>{{emp.mobile}}</td>
	    			<td>{{emp.email}}</td>
	    			<td><a href="{% url 'quickapp:adminemployerdelete' emp.id %}">Delete</a></td>
	    		</tr>
	    		{% endfor %}
	    	</tbody>
	    </table>
	</div>
</div>



<div class="error-btn">
 <a class="read fourth" href="{% url 'quickapp:adminhome' %}">Return to Home</a>
</div>





{% endblock %}

templates/admintemplates/adminjobcategorycreate.html
{% extends 'admintemplates/adminbase.html' %}
{% block createcategory %} active {% endblock %}

{% block content %}

<!--/forms-->
													<div class="forms-main">
														<h2 class="inner-tittle">Create Category </h2>
															<div class="graph-form">
																	<div class="form-body">
																		<form method="POST" enctype="multipart/form-data">
																			{% csrf_token %}
			                                                                {{form.as_p}}
																		<div class="checkbox"> <label> <input type="checkbox"> Check me out </label> </div> <button type="submit" class="btn btn-default">Submit</button> </form> 
																	</div>

															</div>



															
<div class="error-btn">
 <a class="read fourth" href="{% url 'quickapp:adminhome' %}">Return to Home</a>
</div>

{% endblock %}

templates/admintemplates/adminjobcategorylist.html
{% extends 'admintemplates/adminbase.html' %}
{% block categorylist %} active {% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3 class="text-center">Category Lists</h3>
	    <table class="table table-bordered">
	    	<head>
	    		<tr>
	    			<th>Title</th>
	    			<th>Image</th>
	    			<th>Action</th>
	    			<th>Action</th>

	    		</tr>
	    	</head>
	    	<tbody>
	    		{% for category in allcategory %}
	    		<tr>
	    			<td><a href="{% url 'quickapp:adminjobcategorydetail' category.id  %}">{{category.title}}</a></td>
                    <td><img src="{{category.image.url}}" class="img-fluid" width="100"></td>
	    			<td><a href="{% url 'quickapp:adminjobcategoryupdate' category.id %}">Update</a></td>
	    			<td><a href="{% url 'quickapp:adminjobcategorydelete' category.id %}">Delete</a></td>
	    		</tr>
	    		{% endfor %}
	    	</tbody>
	    </table>
	</div>
</div>




<div class="error-btn">
 <a class="read fourth" href="{% url 'quickapp:adminhome' %}">Return to Home</a>
</div>


{% endblock %}