quickapp/urls.py
from django.urls import path
from .views import*

app_name="quickapp"
urlpatterns=[


path('login/',LoginView.as_view(),name="login"),

path("logout/",LogoutView.as_view(),name="logout"),


#client
path('',ClientHomeView.as_view(),name="clienthome"),
path('contact/',ClientContactView.as_view(),name="clientcontact"),
path('about/',ClientAboutView.as_view(),name="clientabout"),
path('profession/',ClientProfession.as_view(),name="clientprofession"),
path('events/',ClientEventView.as_view(),name="clientevent"),
path('employerregister/', EregisterView.as_view(),name="employerregister"),
path('jobseekerregister/', JregisterView.as_view(),name="jobseekerregister"),
path('username-checker/', IdCheckerView.as_view(),name="idchecker"),
path('job/<int:pk>/detail', ClientJobDetailView.as_view(),name="jobdetail"),
path("results/", ClientSearchView.as_view(), name="search"),
path("category/<int:pk>/list/", ClientCategoryDetailView.as_view(), name="clientcategorydetail"),





#admin
path("admin/home/",AdminHomeView.as_view(),name="adminhome"),
path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),
path("admin/jobcategory/<int:pk>/detail/",AdminJobCategoryDetailView.as_view(),name="adminjobcategorydetail"),
path("admin/jobcategory/create/",AdminJobCategoryCreateView.as_view(),name="adminjobcategorycreate"),
path("admin/jobcategory/<int:pk>/update/",AdminJobCategoryUpdateView.as_view(),name="adminjobcategoryupdate"),
path("admin/jobcategory/<int:pk>/delete/",AdminJobCategoryDeleteView.as_view(),name="adminjobcategorydelete"),
path("admin/job/list/",AdminJobListView.as_view(),name="adminjoblist"),
path("admin/job/<int:pk>/delete/",AdminJobDeleteView.as_view(),name="adminjobdelete"),
path("admin/job/<int:pk>/detail/",AdminJobDetailView.as_view(),name="adminjobdetail"),
#path("admin/job/category/list/",AdminJobCategoryListView.as_view(),name="adminjobcategorylist"),


path("admin/profile/",AdminProfileView.as_view(),name="adminprofile"),

path("admin/employer/list/",EmployerListView.as_view(),name="employerlist"),
path("admin/employers/list/",AdminEmployerListView.as_view(),name="adminemployerlist"),
path("admin/employer/<int:pk>/detail/",AdminEmployerDetailView.as_view(),name="adminemployerdetail"),
path("admin/employer/<int:pk>/delete/",AdminEmployerDeleteView.as_view(),name="adminemployerdelete"),

path("admin/jobseeker/list/",AdminJobSeekerListView.as_view(),name="adminjobseekerlist"),
path("admin/jobseeker/<int:pk>/detail",AdminJobSeekerDetailView.as_view(),name="adminjobseekerdetail"),
path("admin/jobseeker/<int:pk>/delete/",AdminJobSeekerDeleteView.as_view(),name="adminjobseekerdelete"),


path("admin/slideshow/list/", AdminSlideShowListView.as_view(), name='adminslideshowlist'),
path("admin/slideshow/create/", AdminSlideShowCreateView.as_view(), name='adminslideshowcreate'),
path("admin/slideshow/<int:pk>/update/", AdminSlideShowUpdateView.as_view(), name='adminslideshowupdate'),
path("admin/slideshow/<int:pk>/delete/", AdminSlideShowDeleteView.as_view(), name='adminslideshowdelete'),


#employer
path("employer/home/",EmployerHomeView.as_view(),name="employerhome"),
path("employer/dashboard/",EmployerDashBoardView.as_view(),name="employerdashboard"),
path("employer/jobs/create/",EmployerJobCreateView.as_view(),name="employerjobcreate"),
path('employer/job/<int:pk>/delete/',EmployerJobDeleteView.as_view(), name="employerjobdelete"),
path('employer/job/<int:pk>/update/',EmployerJobUpdateView.as_view(), name="employerjobupdate"),
path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/jobs/<int:pk>/detail/",EmployerJobDetailView.as_view(),name="employerjobdetail"),
# path("employer/<int:pk>/detail/",EmployerOwnDetailView.as_view(),name="employerowndetail"),

path("employer/category/",EmployerCategoryView.as_view(),name="employercategory"),
path("employer/category/create/",EmployerCategoryCreateView.as_view(),name="employercategorycreate"),
path('employer/category/<int:pk>/delete/',EmployerCategoryDeleteView.as_view(), name="employercategorydelete"),
path('employer/category/<int:pk>/update/',EmployerCategoryUpdateView.as_view(), name="employercategoryupdate"),
path("employer/logout/",EmployerLogoutView.as_view(),name="employerlogout"),





path("search/",EmployerSearchView.as_view(),name="employersearch"),

path("employer/home/jobs/list/",EmployerHomeJobListView.as_view(),name="employerhomejoblist"),
path("employer/category/list/",EmployerCategoryListView.as_view(),name="employercategorylist"),
path("employer/category/<int:pk>/detail/",EmployerCategoryDetailView.as_view(),name="employercategorydetail"),
path("employer/profile/<int:pk>/detail/",EmployerprofileDetailView.as_view(),name="employerprofile"),
path("employer/jobseeker/<int:pk>/detail/",EmployerJobseekerDetailView.as_view(),name="employerjobseeker"),
path("jobseeker/jobseekerapplied/", JobSeekerJobappliedmessagelView.as_view(), name="jobmessage"),











# jobseeker
path("jobseeker/home/",JobSeekerHomeView.as_view(),name="jobseekerhome"),
path("jobseeker/profile/list/",JobSeekerProfileListView.as_view(),name="jobseekerprofilelist"),

path("jobseeker/profile/detail/",JobSeekerProfileDetailView.as_view(),name="jobseekerprofiledetail"),
path("profile/detail/",ProfileDetailView.as_view(),name="profiledetail"),
path("jobseeker/profile/<int:pk>/update/",JobSeekerProfileUpdateView.as_view(),name="jobseekerprofileupdate"),
path("jobseeker/profile/<int:pk>/delete/",JobSeekerProfileDeleteView.as_view(),name="jobseekerprofiledelete"),


path("job/<int:pk>/apply",JobSeekerJobApplyView.as_view(),name="jobseekerjobapply"),


path("jobseeker/job/list",J_ApplyListView.as_view(),name="jobseekerjoblist"),
path("jobseeker/job/<int:pk>/detail",JobSeekerJobDetailView.as_view(),name="jobseekerjobdetail"),

#contact
path("contact/create/",ContactCreateView.as_view(),name="contactcreate"),
path("contact/list/",ContactListView.as_view(),name="contactlist"),
path("contact/<int:pk>/update/",ContactUpdateView.as_view(),name="contactupdate"),


#about
path("about/create/",AboutCreateView.as_view(),name="aboutcreate"),
path("about/list/",AboutListView.as_view(),name="aboutlist"),
path("about/<int:pk>/update/",AboutUpdateView.as_view(),name="aboutupdate"),




]

quickproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('',include("quickapp.urls")),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/jobseekertemplates/appliedjobdetail.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}


{% endblock %}

templates/jobseekertemplates/jobapplyform.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}
		<!-- banner -->
	<div class="inner_page_agile">
		<h3>Apply now</h3>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="/">Home</a><span>|</span></li>
				<li>Job Application Form</li>
			</ul>
		</div>
	</div>
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info_agileits">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle three">Apply Now </h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="signin-form">
					<div class="login-form-rec">
						<form method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							{{form.as_p}}
							<br><br> 
<!-- 							{{form.username}}
							{{form.password}}
							{{form.confirm_password}}
							{{form.full_name}}
							{{form.company_name}}
							{{form.phone}}
							{{form.mobile}}
							{{form.email}}
							{{form.website}}
							{{form.address}}
							{{form.about}}
							{{form.estd_date}}
							{{form.location}} -->
							<input type="submit" value="confirm">
						</form>
					</div>
					<p class="reg"><a href="#"> By clicking Apply, I agree to your terms</a></p>

				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/jobseekertemplates/jobseekerbase.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
	<title>Soft a Human Resource Management Category Bootstrap Responsive Web Template | Home :: w3layouts</title>
	<!--/tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--//tags -->
	<link href="{% static 'clientstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'clientstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />

	<link href="{% static 'clientstatic/css/font-awesome.css' %}" rel="stylesheet">
	<!-- //for bootstrap working -->
	<link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">
	<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic'
	    rel='stylesheet' type='text/css'>
</head>

<body>
	<!-- header -->
	<div class="header" id="home">
		<div class="content white agile-info">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
						<a class="navbar-brand" href="index.html">
							<h1><span class="fa fa-signal" aria-hidden="true"></span> Quick Jobs <label>Site</label></h1>
						</a>
					</div>
					<!--/.navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								<li class="active"><a href="{% url 'quickapp:jobseekerhome' %}" class="effect-3">Home</a></li>
								
								
								<li><a href="/jobseeker/job/apply" class="effect-3">Apply</a></li>

								
								<li><a href="" class="effect-3">About</a></li>

								{% if request.user.is_authenticated %}
								<li class="nav-item">
								</li>
								<a class="nav-link" href="/logout/">Logout</a><span> (logged in as: {{request.user.username}})</span>
								{% else %} 
								<li class="nav-item {% block login %} {% endblock %}">
									<a class="nav-link" href="/login/">Login<span class="sr-only">(current)</span></a>
								</li>

								{% endif %}


							</ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>
	</div>

	{% block content %}

	{% endblock %}


	<!-- footer -->
	<div class="footer_top_agileits">
		<div class="container">
			<div class="col-md-4 footer_grid">
				<h3>About Us</h3>
				<p>Nam libero tempore cum vulputate id est id, pretium semper enim. Morbi viverra congue nisi vel pulvinar posuere sapien
					eros.
				</p>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Latest News</h3>
				<ul class="footer_grid_list">
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Lorem ipsum neque vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Lorem ipsum neque, vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Lorem ipsum neque, vulputate </a>
					</li>
				</ul>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Contact Info</h3>
				<ul class="address">
					<li><i class="fa fa-map-marker" aria-hidden="true"></i>8088 USA, Honey block, <span>New York City.</span></li>
					<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="fa fa-phone" aria-hidden="true"></i>+09187 8088 9436</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="footer_grids">
				<div class="col-md-4 footer_grid_left">
					<h3>Sign up for our Newsletter</h3>
				</div>
				<div class="col-md-8 footer_grid_right">

					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter Email Address..." required="">
						<input type="submit" value="Submit">
					</form>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<div class="footer_w3ls">
		<div class="container">
			<div class="footer_bottom">
				<div class="col-md-9 footer_bottom_grid">
					<div class="footer_bottom1">
						<a href="index.html">
							<h2><span class="fa fa-signal" aria-hidden="true"></span> Soft <label>Hr Agency</label></h2>
						</a>
						<p>© 2017 Soft. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
					</div>
				</div>
				<div class="col-md-3 footer_bottom_grid">
					<h6>Follow Us</h6>
					<div class="social">
						<ul>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-rss"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>

		</div>
	</div>
	<!-- //footer -->

	<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- js -->
	<script type="text/javascript" src="{% static 'clientstatic/js/jquery-2.1.4.min.js' %}"></script>

	<script type="text/javascript" src="{% static 'clientstatic/js/bootstrap.js' %}"></script>
</body>

</html>

templates/jobseekertemplates/jobseekerhome.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}

{% block content %}
	<!-- banner -->
	<div class="inner_page_agile">
		<h3>Professionals</h3>
		<p>Add Some Short Description</p>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="index.html">Home</a><span>|</span></li>
				<li>Professionals</li>
			</ul>
		</div>
	</div>

<h3>this is jobseeker home page</h3>
<a href="{% url 'quickapp:jobseekerprofiledetail' %}">My Profile</a>

{% endblock %}

templates/jobseekertemplates/jobseekerjoblist.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}
<h5>########################</h5>

{% endblock %}

templates/jobseekertemplates/jobseekerprofilecreate.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}

<div class="row">
	<div class="col-md-8 mx-auto">
		<div class="inner_sec_grids_info_w3ls">
			<div class="signin-form">

				<div class="login-form-rec">
					<form method="POST" enctype="multipart/form-data" >
						{% csrf_token %}
						{{form.username}}
						{{form.password}}
						{{form.confirm_password}}
						<span id="password_massege"></span>
						{{form.full_name}}
						<span style="float:left;width:100%;height:45px;border:1px solid #ccc;margin-left:0px;padding-top:5px">
						Profile Picture : 
							<span style="float:right;width:60%;height:45px;margin-left:87px">
								{{form.image}}
							</span>
						</span>
						<br><br>
						{{form.email}}
						{{form.mobile}}
						{{form.address}}
						{{form.dob}}
						{{form.education}}
						{{form.skill}}
						<span style="float:left;width:100%;height:45px;border:1px solid #ccc;margin-left:0px;padding-top:5px">
						CV : 
							<span style="float:right;width:60%;height:45px;margin-left:87px">
								{{form.cv}}
							</span>
						</span>
						<input type="submit" value="Done" id="save_button">
					</form>
				</div>
			</div>
		</div>

	</div>
</div>


{% endblock %}

templates/jobseekertemplates/jobseekerprofiledetail.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}

{% block content %}


	<!-- banner -->
	<div class="inner_page_agile">
		<h3>Professionals</h3>
		<p>Add Some Short Description</p>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="index.html">Home</a><span>|</span></li>
				<li>Professionals</li>
			</ul>
		</div>
	</div>
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info_agileits">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">Candidates </h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-8 job_info_left">
					<div class="tab_grid_prof">
						<div class="col-sm-3 loc_1">
							<a href="single.html"><img src="images/pf1.jpg" alt=""></a>
						</div>
						<div class="col-sm-9">
							<div class="location_box1">
							{% for jobseekerdetail in jobseekerdetails %}								
								<h6>Profile of {{jobseekerdetail}}</h6>
								<span class="m_2_prof">Web Developer at Highest Dreams Inc</span>
								<div class="person-info">
									<ul>

										<h3><b>Name: </b>{{jobseekerdetail.full_name}}</h3>
										<p>Address: {{jobseekerdetail.address}}</p>
										<p>Contact Info: {{jobseekerdetail.mobile}}</p>
										<p>Email: {{jobseekerdetail.email}}</p>
										<p>Education: {{jobseekerdetail.education}}</p>
										<p>Skill: {{jobseekerdetail.skill}}</p>
										<p>DOB: {{jobseekerdetail.dob}}</p>
										<p>CV: {{jobseekerdetail.cv}}</p>
									</ul>
								</div>
							

								<div class="read">
									<a href="{% url 'quickapp:jobseekerprofileupdate' jobseekerdetail.id %}" class="read-more"> Edit</a>
								</div>
								{% endfor %}
								<ul class="top-btns">
									<li><a href="#" class="fa fa-plus toggle"></a></li>
									<li><a href="#" class="fa fa-star"></a></li>
									<li><a href="#" class="fa fa-link"></a></li>
								</ul>

							</div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
			</div>
		</div>
	</div>
					




{% endblock %}

templates/jobseekertemplates/jobseekerprofilelist.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% block content %}
	<!-- banner -->
	<div class="inner_page_agile">
		<h3>Professionals</h3>
		<p>Add Some Short Description</p>

	</div>
	<!--//banner -->
	<!--/w3_short-->
	<div class="services-breadcrumb_w3layouts">
		<div class="inner_breadcrumb">

			<ul class="short_w3ls"_w3ls>
				<li><a href="index.html">Home</a><span>|</span></li>
				<li>Professionals</li>
			</ul>
		</div>
	</div>
<div class="row">
	<div class="col-md-12">
		{{thisuser.full_name}}pravin ****************
<!-- 	    <table class="table table-bordered">
	    	<head>
	    		<tr>
	    			<th>SN</th>
	    			<th>Full Name</th>
	    			<th>Email</th>
	    			<th>Mobile</th>
	    			<th>Address</th>

	    		</tr>
	    	</head>
	    	<tbody>
	    		{% for j_p_dlist in j_profilelist %}
	    		<tr>
	    			<td>{{forloop.counter}}</td>
	    			<td><a href="{% url 'quickapp:jobseekerprofiledetail' j_p_dlist.id %}">{{j_p_dlist.full_name}}</a></td>
	    			<td>{{j_p_dlist.email}}</td> 
	    			<td>{{j_p_dlist.mobile}}</td>
	    			<td>{{j_p_dlist.address}}</td>
	    		</tr>
	    		{% endfor %}
	    	</tbody>
	    </table> -->
	</div>
</div>



{% endblock %}